### ISSUE TITLE
Use case diagram

### ISSUE THREAD

**Issue by BaranekD** [BaranekD/pa165-blue-bat#3]
Jedním z úkolů je vytvořit use case diagram. Ten musí obsahovat alespoň dve role. Myslím, že se dá přímo řídit popisem našeho projektu na https://is.muni.cz/auth/el/fi/jaro2021/PA165/seminars.qwarp?prejit=6497214

**Comment by MrJumpl** [comment]
Vytvořil jsem první dvě verze diagramu:

1. Jednodušší verze, která přesně odpovídá popisu systému 
![pa165_use_case_2](https://user-images.githubusercontent.com/55142093/112233571-fcab2b00-8c3a-11eb-8e65-8128c8c34d87.png)

2. Rozšířená verze, která spíš odpovídá běžné situaci, kdy se stálý zákazník může registrovat, aby nemusel stále vyplňovat své osobní informace a měl by jistotu správného vyplnění osobních dat. Navíc by mohl zrušit svou rezervaci. 
![pa165_use_case](https://user-images.githubusercontent.com/55142093/112233717-2ebc8d00-8c3b-11eb-8e20-130825c9d8d9.png)

Který preferujete? Popřípadě nějaké návrhy na vylepšení?

**Comment by BaranekD** [comment]
Super, ani k jednomu nic nemám, přijdou mi v pohodě. Jinak vzhledem k projektu bych se možná snažil to držet as simple as possible, i když v realitě by to třeba neobstálo. Proto bych byl asi spíš pro první variantu. Pořád je cílem hlavně naučit se s danými technologiemi a na to ten první diagram bude úplně stačit. Jediné co mě napadá je, že by se tam adminovi mohla přidat ještě možnost smazání rezervace. Myšlenka za tím je taková, že přímo customer to pochopitelně udělat nemůže, ale tu možnost by mít měl. Tak by mohl třeba nějak "mimo systém" kontaktovat admina (reálně by psal/volal dejme tomu na nějaký helpdesk), který by po prokázání totožnosti (máme o každěm zákazníkovi uložené informace v jedné z entit, takže to jsme schopni ověřit) danou rezervaci zrušil. Co myslíte?

Jinak bych počkal ještě jak se vyjádří ostatní, pokud budou spíše pro druhou variantu, může být. Jen je třeba počítat s tím, že by to bylo víc práce.

**Comment by MrJumpl** [comment]
Mazání rezervace tam je (vlevo nahoře od vytvoření rezervace 🙂 možná bych mohl prohodit jejich pořadí, aby to bylo lépe čitelné). Taky mi to přijde rozumné, aby admin mohl mazat rezervace.

**Comment by BaranekD** [comment]
Moje chyba, přehlédnul jsem to, sorry. V tom případě to za mě jě takhle úplně v pohodě

**Comment by ondrejvaca** [comment]
Use case diagramy jsou za mě v pořádku. A osobně bych taky byl zprvu pro jednodušší verzi,  "šperkovat" můžeme začít vždycky.

**Comment by Madoran** [comment]
Verím ze je to v poriadku, jedine co nám asi mozu vytknut v jednoduchšej verzii je asi to ze po vytvorení tripu to nemozu vidieť alebo nejak editovat, ale to sa vždy moze nejako doplniť. Ja by som tiež začal co najjednoduchšie.
