### ISSUE TITLE
Class diagram

### ISSUE THREAD

**Issue by BaranekD** [BaranekD/pa165-blue-bat#4]
Je třeba vytvořit class diagram k projektu obsahující naše entity classy. Tyto entity lze převzít přímo z popisu projektu: https://is.muni.cz/auth/el/fi/jaro2021/PA165/seminars.qwarp?prejit=6497214

**Comment by ondrejvaca** [comment]
![classdiagram2](https://user-images.githubusercontent.com/80227719/114529728-8c486600-9c4a-11eb-8444-49c0c03a2aee.png)
