### ISSUE TITLE
Vytvoření wiki projektu

### ISSUE THREAD

**Issue by BaranekD** [BaranekD/pa165-blue-bat#5]
Je potřeba vytvořit projektovou wiki. Ta bude obsahovat nějaký základní popis našeho projektu, use case diagram a class diagram. Tento task je závislý na splnění "Use case diagram" a "Class diagram" tasků (pokud přijdu na to, jak se na ně odsud odkázat, udělám to, zatím to musí stačit takhle).

**Comment by Madoran** [comment]
Ja mozem skusit urobit wiki, mam to urobit Anglicky alebo slovensky ?
